{
 "title": "GPU Global",
 "description": "Focused view of all GPUs in K3s cluster",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU Temperature",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP",
     "legendFormat": "{{modelName}} {{gpu}} - {{Hostname}}"
    }
   ]
  },
  {
   "title": "Avg GPU Node Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(Hostname) (DCGM_FI_DEV_GPU_TEMP)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Temperature Timeline",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_TEMP", "legendFormat": "{{modelName}} {{gpu}}" }
   ]
  },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "GPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL",
     "legendFormat": "{{modelName}} {{gpu}} - {{Hostname}}"
    }
   ]
  },
  {
   "title": "Avg GPU Node Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(Hostname) (DCGM_FI_DEV_GPU_UTIL)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Utilization Timeline",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL", "legendFormat": "{{modelName}} {{gpu}}" }
   ]
  },
  { "title": "GPU Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "GPU Memory Utilization",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED/(DCGM_FI_DEV_FB_FREE+DCGM_FI_DEV_FB_USED)",
     "legendFormat": "{{modelName}} {{gpu}} - {{Hostname}}"
    }
   ]
  },
  {
   "title": "Avg GPU Node Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(Hostname) (DCGM_FI_DEV_FB_USED / (DCGM_FI_DEV_FB_USED + DCGM_FI_DEV_FB_FREE))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Utilization Timeline",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED / ( DCGM_FI_DEV_FB_USED + DCGM_FI_DEV_FB_FREE )",
     "legendFormat": "{{modelName}} {{gpu}}"
    }
   ]
  },
  { "title": "Power Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "GPU Watts",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE",
     "legendFormat": "{{modelName}} {{gpu}} - {{Hostname}}"
    }
   ]
  },
  {
   "title": "Total GPU Node Power Draw",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(Hostname) (DCGM_FI_DEV_POWER_USAGE)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Watts Timeline",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_POWER_USAGE", "legendFormat": "{{modelName}} {{gpu}}" }
   ]
  }
 ]
}