{
 "title": "GPU Nodes",
 "description": "Dashboard to visualize data from the NVIDIA Data Center GPU Manager (DCGM)",
 "tags": [
  "IB",
  "GPU"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname_name",
    "label": "Host",
    "query": "label_values(node_textfile_mtime_seconds{file=\"dcgm.prom\"}, instance)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(node_uname_info{instance=~\"$hostname_name:(.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"$hostname\"}",
     "legendFormat": "1min"
    },
    {
     "expr": "node_load5{instance=\"$hostname\"}",
     "legendFormat": "5min"
    },
    {
     "expr": "node_load15{instance=\"$hostname\"}",
     "legendFormat": "15min"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "dcgm_power_usage{instance=\"$hostname\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Total Power",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 0 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dcgm_power_usage{instance=\"$hostname\"})"
    }
   ]
  },
  {
   "title": "NVLINK Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dcgm_nvlink_bandwidth_total{instance=\"$hostname\"}[$__interval]))",
     "legendFormat": "Total"
    },
    { "expr": "dcgm_nv" }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$hostname\"} - node_memory_MemFree_bytes{instance=\"$hostname\"} - node_memory_Buffers_bytes{instance=\"$hostname\"} - node_memory_Cached_bytes{instance=\"$hostname\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$hostname\"}",
     "legendFormat": "Buffered"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$hostname\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$hostname\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "dcgm_gpu_temp{instance=\"$hostname\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Avg. Temperature",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 5 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(dcgm_gpu_temp{instance=\"$hostname\"})"
    }
   ]
  },
  {
   "title": "PCIe Throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 5 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "irate(dcgm_pcie_tx_throughput{instance=\"$hostname\"}[$__interval])",
     "legendFormat": "GPU{{gpu}}_Tx"
    },
    {
     "expr": "irate(dcgm_pcie_rx_throughput{instance=\"$hostname\"}[$__interval])",
     "legendFormat": "GPU{{gpu}}_Rx"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1-(sum(node_filesystem_avail_bytes{device!=\"rootfs\",instance=\"$hostname\"} / node_filesystem_size_bytes{device!=\"rootfs\",instance=\"$hostname\"}))/count(node_filesystem_avail_bytes{device!=\"rootfs\",instance=\"$hostname\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"$hostname\"} - node_memory_MemFree_bytes{instance=\"$hostname\"} - node_memory_Buffers_bytes{instance=\"$hostname\"} - node_memory_Cached_bytes{instance=\"$hostname\"}) / node_memory_MemTotal_bytes{instance=\"$hostname\"}) * 100"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "dcgm_gpu_utilization{instance=\"$hostname\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Total Utilization",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(dcgm_gpu_utilization{instance=\"$hostname\"})"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$hostname'}[$__interval])*8 or irate(node_network_receive_bytes{instance=~'$hostname'}[$__interval])*8",
     "legendFormat": "{{device}}_In"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$hostname'}[$__interval])*8 or irate(node_network_transmit_bytes{instance=~'$hostname'}[$__interval])*8",
     "legendFormat": "{{device}}_Out"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~'$hostname'}[5m]) or irate(node_disk_sectors_written{instance=~'$hostname'}[5m]) * 512",
     "legendFormat": "{{device}}_write"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~'$hostname'}[5m]) or irate(node_disk_sectors_read{instance=~'$hostname'}[5m]) * 512",
     "legendFormat": "{{device}}_read"
    }
   ]
  },
  {
   "title": "GPU Mem Cpy Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "dcgm_mem_copy_utilization{instance=\"$hostname\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Total Mem Cpy Utilization",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(dcgm_mem_copy_utilization{instance=\"$hostname\"})"
    }
   ]
  },
  {
   "title": "InfiniBand Throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 15 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_infiniband_port_data_transmitted_bytes_total{instance=\"$hostname\",device!~\"hfi.+\"}[$__interval])*8 or irate(node_infiniband_port_data_transmitted_bytes_total{instance=\"$hostname\",device=~\"hfi.+\"}[$__interval])*8*2",
     "legendFormat": "{{device}}_Out"
    },
    {
     "expr": "irate(node_infiniband_port_data_received_bytes_total{instance=\"$hostname\",device!~\"hfi.+\"}[$__interval])*8 or irate(node_infiniband_port_data_received_bytes_total{instance=\"$hostname\",device=~\"hfi.+\"}[$__interval])*8*2",
     "legendFormat": "{{device}}_In"
    }
   ]
  },
  {
   "title": "Hostname",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 20 },
   "format": "hertz",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_uname_info{instance=\"$hostname\"}"
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 20 },
   "format": "hertz",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_uname_info{instance=\"$hostname\"}"
    }
   ]
  },
  {
   "title": "GPU Mem Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "dcgm_fb_used{instance=\"$hostname\"}/(dcgm_fb_used{instance=\"$hostname\"}+dcgm_fb_free{instance=\"$hostname\"})",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "System Power Draw",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 20 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_hwmon_power_average_watt{instance=\"$hostname\"}"
    }
   ]
  },
  {
   "title": "System Power Draw",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 20 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_power_average_watt{instance=\"$hostname\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 22 },
   "format": "hertz",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(dcgm_sm_clock{instance=\"$hostname\"}*1000000)"
    }
   ]
  },
  {
   "title": "GPU Memory Clocks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 22 },
   "format": "hertz",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(dcgm_memory_clock{instance=\"$hostname\"}*1000000)"
    }
   ]
  }
 ]
}